### ISSUE TITLE
'Your dinners'

### ISSUE THREAD

**Issue by amd112** [amd112/dukeConversations#10]
create 'your dinners' status banner on login home page (populate the rest of it with upcoming dinners?)

**Comment by kne3** [comment]
Is this still something we want on the page or is the future dinners you added enough?

**Comment by amd112** [comment]
Hmmm. It would probably be good to have a section where there's a status of the dinners they've applied to. 

So I guess show all the applications for dinners in the future, and just say the date and if they've been chosen?

**Comment by amd112** [comment]
All works except for filtering the correct applications to feed to the login page. I realized that I had been sending it Applications.objects.filter(~is the person).filter(~date is from now until +20 days) but that was selecting applications from now and future. 

Need to select applications.objects.filter(~is the person).filter(~has a dinner id whose dinner is now until +20 days)
