### ISSUE TITLE
Enable travis for continuous integration?

### ISSUE THREAD

**Issue by sarpu** [amd112/dukeConversations#13]
I saw a .travis.yml file in Htmlcsswork, but I don't think we have CI now. It might be helpful to keep us bugfree :)

**Comment by amd112** [comment]
@sarpu How would we implement this? Do you want to take lead on this since you seem to know about it?

**Comment by sarpu** [comment]
Of course, but I cannot enable it since you are the owner, so could you also make me an owner?

**Comment by kne3** [comment]
since project is almost done there's really no need for this I would think. Feel free to reopen if I'm wrong
