### ISSUE TITLE
Figure out emailing system

### ISSUE THREAD

**Issue by amd112** [amd112/dukeConversations#14]

**Comment by amd112** [comment]
can send emails now, need to create template and automatic emails when 
1) person submits registration 
2) when selection decision is made

**Comment by amd112** [comment]
Add/edit the user email when they edit their profile

EDIT: done

**Comment by amd112** [comment]
@kne3 Where do you assign the email that it sends from? In views I'm still seeing the Kimberly3 domain, which I think you said no longer works?

**Comment by kne3** [comment]
It comes from DukeConversation@gmail.com. That line I don't think actually does anything, the actually assignment is in the settings.py file.

**Comment by amd112** [comment]
Now send an email to a user on signup for a dinner, just with text in the body of professor name and topic. Now we just need to send something useful.

**Comment by amd112** [comment]
Email works!

![image](https://user-images.githubusercontent.com/19820865/33461780-006e3360-d602-11e7-8eee-582da8dfe134.png)
