### ISSUE TITLE
Aesthetics on form pages

### ISSUE THREAD

**Issue by amd112** [amd112/dukeConversations#2]
The form pages don't have the CSS stuff working. How can we make the generated elements maintain the ~pretty~
See the '/signup' page for an example, but will be relevant to all form pages.

**Comment by amd112** [comment]
Also how to mask password text on the generated components

**Comment by kne3** [comment]
Aesthetics on form pages have more or less been fixed and the password on the login page is masked.

**Comment by amd112** [comment]
Hey y'all so I was getting the formatting to work on the input boxes (which at least it does so net neutral) and I fucked something up and nothing is centered anymore but idk what it is help

**Comment by kne3** [comment]
@amd112  Which pages is this on? I fixed the sign up dinner page so everything is centered now but wasn't sure if was the page you were referring to? Wanna fix them all before I push and submit.

**Comment by amd112** [comment]
I think the edit is also a bit off, the text is centered, but the form itself is a little off idk sorry just saw this

**Comment by kne3** [comment]
Ok! Edit and sign up for dinner have been fixed, I think thats all of them that needed to be fixed, so I'm closing this but if I'm wrong, just let me know what other pages need to be fixed.
