### ISSUE TITLE
password recovery

### ISSUE THREAD

**Issue by amd112** [amd112/dukeConversations#22]
1) be able to send email
2) send email with temp password and set password to that
3) create a reset password page where they enter the password

**Comment by amd112** [comment]
https://stackoverflow.com/questions/24935271/django-custom-user-email-account-verification

Could also use this method to verify emails before letting ppl register for dinners

**Comment by amd112** [comment]
Can you give me a pointer to where this is implemented so I can try to get up to speed?

**Comment by kne3** [comment]
If you click the forgot password button on login, it will take you through the process. Still in the process of fixing the formatting of the pages though. The pages are all password_reset_"something"

**Comment by kne3** [comment]
The system is set up and works.
