### ISSUE TITLE
How do we differentiate professors?

### ISSUE THREAD

**Issue by sarpu** [amd112/dukeConversations#28]
So currently the model for professors looks like below:

```
class Professor(models.Model):
	genders = (
		("1", "M"),
		("2", "F"),
		("3", "O")
	)
	name = models.CharField(max_length = 40)
	food_restrictions = models.CharField(max_length = 50, null = True, blank = True)
	gender = models.CharField(max_length = 5, choices = genders)
	def __str__(self):
		return self.name
```
In cases where we have two professors with the same name, how do we differentiate between them? I see that in our schema we included an id field, but I am pretty sure that supposes something like a unique ID. So perhaps we should add that @amd112 ? Because even though internally we never overwrite two professors (since django automatically generates id fields since we did not declare any pks for this model), we cannot differentiate between them.

**Comment by amd112** [comment]
You're right, we should enforce uniqueid as a primary key. I can do it tonight but if you're working, you can just flush the system, add the key and then migrate.

**Comment by amd112** [comment]
And we should also enforce that it be exactly 7 characters, which I think we didn't do on student either woops

**Comment by amd112** [comment]
Given we're looking at models we might want to also reconsider the on_delete's we put in @nhb8  I know we had talked about that, thoughts?

**Comment by amd112** [comment]
shoot also we should link the username in the student table as foreign key in the user table now that we have that

**Comment by sarpu** [comment]
Gotcha, I'll make the appropriate changes, I just wanted to confirm I wasn't missing anything. Also, even though we are using composite keys, django doesn't support composite keys, so unless we declare a pk for each model, it simply passes the whole object whenever we use the said object. I don't think this is an issue at the moment, but I wasn't aware of this behavior, so I think it's good we know this.

**Comment by amd112** [comment]
Already changed! The way we are dealing with the composite key issue is a unique_together call. That maintains that the combo of the attributes is unique and puts an index on the other columns.
