### ISSUE TITLE
Change name of site from TestSite to something more appropriate

### ISSUE THREAD

**Issue by kne3** [amd112/dukeConversations#29]

**Comment by amd112** [comment]
I don't see TestSite anywhere, what is this?

**Comment by kne3** [comment]
The emails the password recovery sends out has some {{site}} things in the subject line (there were also some in the body but I just got rid of that) and the site name in that is TestSite.

**Comment by kne3** [comment]
Fixed subject line, which was easier than finding where the site name is stored
