### ISSUE TITLE
Sign up for dinner is broken

### ISSUE THREAD

**Issue by kne3** [amd112/dukeConversations#32]
The page gives an error when you try to click on it

**Comment by sarpu** [comment]
Fixed it. I hope I didn't mess up the db again tho

**Comment by kne3** [comment]
The whole thing no longer compiles :(

**Comment by amd112** [comment]
Lol you opened right after I committed, should be fine now

**Comment by kne3** [comment]
Lol my bad

**Comment by sarpu** [comment]
Wait what happened?
