### ISSUE TITLE
error on register page

### ISSUE THREAD

**Issue by amd112** [amd112/dukeConversations#36]
UnboundLocalError
local variable 'options' referenced before assignment
C:\Users\Anne\Documents\Duke\DukeFall2017\CS 316\dukeConversations\site\convos\app\forms.py in __init__, line 74

form = registerDinner(user=user) ...
C:\Users\Anne\Documents\Duke\DukeFall2017\CS 316\dukeConversations\site\convos\app\forms.py in __init__
		self.fields['dinner'].choices = options

**Comment by kne3** [comment]
I don't get this error when I register a new account or register for a dinner (not sure which register page you were referring to). Do you still get this error?

**Comment by amd112** [comment]
sorry for the delay - I meant registering for a dinner. Let me try to replicate the error.

**Comment by amd112** [comment]
error was in the AdminSite branch only, fixed it!
