### ISSUE TITLE
Host the website online?

### ISSUE THREAD

**Issue by kne3** [amd112/dukeConversations#37]
Do we need to host our site online instead of just locally?

**Comment by sarpu** [comment]
If you could checkout a vm and give me the access credentials I can set up a server if needed.

**Comment by sarpu** [comment]
@amd112 if you are not using yours do you mind going to [https://vcm.duke.edu/](url), reserving a machine and passing me the credentials? I am using mine for another class project.

**Comment by amd112** [comment]
what os do you want

**Comment by sarpu** [comment]
16.04

**Comment by amd112** [comment]
created. what info do you need

**Comment by sarpu** [comment]
Could you facebook message me the admin password

**Comment by amd112** [comment]
done!

**Comment by amd112** [comment]
Sarp how's it going? 

Will we all be able to access it like a production site on the VM? If not should we consider looking in to Heroku or something?

**Comment by sarpu** [comment]
Yes we will be able to access. I just need to turn in some hw thats due tonight and then I'll set it up.

**Comment by sarpu** [comment]
The website should now be running at the url below.
[http://vcm-2370.vm.duke.edu](url)
(I don't know why but clicking the link through here takes you to github's 404. Just copy paste the link pls)

**Comment by amd112** [comment]
@sarpu can you give us some info on how this connects to the github? eg can we still push data to it?

**Comment by amd112** [comment]
also can we change to the production settings, or at least turn off debug =true

**Comment by sarpu** [comment]
You can totally push. All we need to do is log in, do a git pull and reboot, after which the it has the latest changes.  Also yes, I'll turn off debug

**Comment by amd112** [comment]
lit lit this is great!
