### ISSUE TITLE
uniqueid verification broken

### ISSUE THREAD

**Issue by amd112** [amd112/dukeConversations#39]
I think maybe I didn't commit that work idk but it doesn't check to make sure that the unique id is the right length

**Comment by amd112** [comment]
Anyone with ideas on this appreciated @sarpu @kne3 @nhb8 @SummerSmith 
Validators on models and forms both seem to break everything, and all the documentation I find for them isn't for 1.11. Model fields can only have a max, not a min length. 

Basically need to enforce that unique id is 7 long, phone is 10 long, and netid is at least... 3? Ideas?

**Comment by sarpu** [comment]
Ok, I added validation for that, and we can add more for all the others as well.
