### ISSUE TITLE
edit members.txt

### ISSUE THREAD

**Issue by amd112** [amd112/dukeConversations#43]

**Comment by amd112** [comment]
comment when you're done w/ your description

**Comment by kne3** [comment]
Worked predominantly on front end features, allowing the django forms and to display with visually pleasing css formatting and integrate with the previously created bootstrap templates. Additionally, set up the email server, change password and reset password systems.

**Comment by SummerSmith** [comment]
Worked predominantly on front end features, allowing the django forms and to display with visually pleasing css formatting and integrate with the previously created bootstrap templates

**Comment by amd112** [comment]
all there!
