### ISSUE TITLE
Nothing loads locally (400 error), Can't login on vm (500 error)

### ISSUE THREAD

**Issue by amd112** [amd112/dukeConversations#47]

**Comment by sarpu** [comment]
Yeah, I am working to solve the 500 issue rn, but I think it has to do with turning debug to false. Could you try updating your local settings file by adding to the list ALLOWED_HOSTS = ['localhost', ...]

**Comment by amd112** [comment]
mmmm ok well glad we know why 400 is happening! gl w/ 500

**Comment by sarpu** [comment]
Did it work? Also, worst case scenario, I'll switch back to debug=True during demo, I doubt that would be an issue.

**Comment by amd112** [comment]
wait actually it didn't work, nothing loads, all 400 errors

**Comment by amd112** [comment]
manually adding 127.0.0.1 worked for me idk why

**Comment by sarpu** [comment]
So localhost didn't work? Also, after manually adding 127.0.0.1, can you login/register?

**Comment by sarpu** [comment]
Ok, we are back in business, vm is working now. It was a migrations issue. We should find a better workflow to manage these tbh, or I am probably messing something up each time.
