### ISSUE TITLE
Form pages

### ISSUE THREAD

**Issue by amd112** [amd112/dukeConversations#7]
create form pages for signup, review, edit.

**Comment by amd112** [comment]
created edit page.

**Comment by amd112** [comment]
created register page

**Comment by amd112** [comment]
need to create the review page, need to make the models only pass the dinners they've been to and not reviewed

**Comment by sarpu** [comment]
I'll get the review page today.

**Comment by sarpu** [comment]
@amd112 To be clear, a person who did not attend a dinner is someone who was selected for that dinner but does not appear in the attendance table with that dinner?

**Comment by amd112** [comment]
Exactly

To get the things they haven't been reviewed yet you need to get the set of dinners that have their id in the Attendance table, and the set of dinners that are in the Review table and find the difference. Feel free to populate through admin if you wanna test.

**Comment by amd112** [comment]
I was thinking about this again, does anyone remember why we had separated the application file? It doesn't seem to violate BCNF to just have 'attended' be an attribute in the application table, which would make summing what they went to a lot easier. @sarpu @nhb8

**Comment by kne3** [comment]
just a note that on the edit profile page cancel and submit both save the changes. Probably want to fix the cancel button so it doesn't save changes

Edit: fixed it at the expense of it looking not quite as nice. If someone can figure out how to get both nice looking and the function we want that would be ideal

**Comment by sarpu** [comment]
@amd112 I agree, I think I forgot to include attendance in the original schema, then whoever added it just added attendance as its own thing.

**Comment by amd112** [comment]
Fixed the attendance thing @kne3 the cancel thing is solved right?

**Comment by kne3** [comment]
yes we just deleted it lol

**Comment by amd112** [comment]
review url seems to have issues?

**Comment by kne3** [comment]
fixed css

**Comment by amd112** [comment]
shoot I didn't put in all the correct fields in the model yet, my b let me do that real quick

**Comment by amd112** [comment]
ok so the theme of everything is that when I get backend working I break the beauty.
I can't get the radio buttons to align horizontally, I found a fix (https://stackoverflow.com/questions/5935546/align-radio-buttons-horizontally-in-django-forms) but it seems that this method is broken in django 1.11 (https://groups.google.com/forum/#!msg/django-users/tlcXfeSVm00/oU0s254oBAAJ) so idk how to fix it.

**Comment by amd112** [comment]
finally got all the fields in review form properly working, and fixed the signup and review so that a 'there's nothing left to review' note pops up instead of a blank form that doesn't respond to anything

**Comment by amd112** [comment]
OH JK - Review still needs to be edited. When we merge in admin side the application references all need to change to attendance references
