### ISSUE TITLE
output data 

### ISSUE THREAD

**Issue by amd112** [amd112/dukeConversations#9]
create button to output data from the website (on admin end) aka figure out how to create custom admin pages

**Comment by amd112** [comment]
https://www.endpoint.com/blog/2012/02/22/dowloading-csv-file-with-from-django

**Comment by nhb8** [comment]
You can now download csvs from the Admin Selection page, but we should talk about what data exactly we want to be able to output.

**Comment by amd112** [comment]
@nhb8 fixed
